language: java

jobs:
  include:
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        token: $GITHUB_OAUTH
        cleanup: false
        on:
          tags: true
