language: java

jobs:
  include:
    - stage: GitHub Release
      script: skip
      before_deploy:
        - git tag v1.0
      deploy:
        provider: releases
        token: $GITHUB_OAUTH
        file_glob: true
        file: target/*
        skip_cleanup: true
        on:
          tags: false
          branch: main
