language: java

jobs:
  include:
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        token: $GITHUB_OAUTH
        file_glob: true
        file: target/*
        edge: true
        tag_name: v1.0
        on:
          tags: false
          branch: main
