language: java

jobs:
  include:
    - stage: GitHub Release
      script: skip
      before_deploy:
        - git add target/text-transformer-1.0.jar.original
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        token: $GITHUB_OAUTH
        cleanup: false
        on:
          tags: false
          branch: main
