language: Java

jobs:
  include:
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        api_key: "530bea30431ead125af533a70ae4ea3251f2d84a"
        skip_cleanup: true
        on:
          tags: true
